Repository neicnordic/sda-pipeline, pull requests merged in 2020-08, with the labels that each got.

#66 Unittests for storage
  internal/storage/storage.go
  internal/storage/storage_test.go
Labels: go, tests

#69 Tests/config
  cmd/finalize/finalize.go
  cmd/ingest/ingest.go
  cmd/mapper/mapper.go
  cmd/verify/verify.go
  go.sum
  internal/config/config.go
  internal/config/config_test.go
Labels: go, tests

#79 Add default reviewers for DependaBot
  .github/dependabot.yml
Labels: enhancement

#64 Unittests for broker
  .gitignore
  cmd/finalize/finalize.go
  cmd/ingest/ingest.go
  cmd/mapper/mapper.go
  cmd/verify/verify.go
  internal/broker/broker.go
  internal/broker/broker_test.go
  internal/broker/service_mock_test.go
Labels: go, tests

#84 Refactoring/config
  cmd/finalize/finalize.go
  cmd/ingest/ingest.go
  cmd/ingest/ingest_test.go
  cmd/mapper/mapper.go
  cmd/verify/verify.go
  go.mod
  go.sum
  internal/broker/broker.go
  internal/broker/broker_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/database/db.go
  internal/database/db_test.go
  internal/storage/storage.go
  internal/storage/storage_test.go
Labels: enhancement, go
